apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-atp
  labels:
    app.kubernetes.io/name: hello-world-atp
    app.kubernetes.io/instance: hello-world-atp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-world-atp
      app.kubernetes.io/instance: hello-world-atp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-world-atp
        app.kubernetes.io/instance: hello-world-atp
    spec:
      containers:
        - name: hello-world-atp
          image: asia.gcr.io/poc-innovation-iot/hello-world-atp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources: 
            limits: 
              cpu: 64m
              memory: 32Mi
            requests: 
              cpu: 32m
              memory: 6