apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
namespace: atp-training
images:
- name: asia.gcr.io/poc-innovation-iot/hello-world-atp
  newTag: 4cabae53
