apiVersion: v1
kind: Service
metadata:
  name: hello-world-atp
  labels:
    app.kubernetes.io/name: hello-world-atp
    app.kubernetes.io/instance: hello-world-atp
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: hello-world-atp
    app.kubernetes.io/instance: hello-world-atp
